config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
 

  root to: 'static_pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :end_date, :start_date, :title, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :remember_token, :avatar, :avatar_cache
  has_secure_password

  mount_uploader :avatar, AvatarUploader

  # Validaciones
  validates :name, :email, presence: true
  validates :name, length: { maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  # RegExp for email
  validates :email, format: { with: VALID_EMAIL_REGEX},
  									uniqueness: { case_sensitive: false }

  validates_presence_of :password, :password_confirmation
  validates_confirmation_of :password,
                          if: lambda { |m| m.password.present? }

  validates :password, length: {minimum: 6}

  before_save { self.email = email.downcase }

  # LLama al metodo privado create_remember_token
  before_create :create_remember_token

  # Genera un token aleatorio usando urlsafe_base64 de SecureRandom
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Se encripta el token usando SHA1
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    # Método privado que de retorna el atributo remember_token para ser guardado en la base de datos
    # antes de llamar al metodo create
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		# render :new
		user = User.find_by_email(params[:session][:email])

		if user && user.authenticate(params[:session][:password])
			sign_in(user)
      redirect_to user
		else
			flash[:error] = 'Invalid email/password combination'
			render :new
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  	
  end

  def contact
  	
  end
end

app/controllers/users_controller.rb
# encoding: UTF-8
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
    
  end
  def create
  	@user = User.new(params[:user])
  	if @user.save
      # Se logea automáticamente el usuario al rgistrarse, luego es dirigido al perfil del usuario
      sign_in @user
      redirect_to @user, notice: 'Welcome to the Sample App!'
  	else
  		render 'new'
  	end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    # rise 'csbdbbnvbnvn'
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Los datos han sido grabados correctamente'
    else
      flash[:error] = 'Error al actualizar la información'
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Se guarda la cookie
	def sign_in(user)
		# Se crea un remember_token (aleatorio)
		remember_token = User.new_remember_token
		# se crea la cookie como permanente
		cookies.permanent[:remember_token] = remember_token
		# Se actualiza el campo remember_token en tabla users
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		# Se setea current user al nuevo usuario
		self.current_user = user
	end


	# Setter current user
	def current_user=(user)
		@current_user = user
	end

	# getter current_user
	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by_remember_token(remember_token)
	end

	# Verifica si el usuario está o no logeado
	def signed_in?
    !current_user.nil?
  end

  def sign_out
  	#Se actualiza el remember_token
  	current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
  	# Se elimina la cookie
  	cookies.delete(:remember_token)
  	# Se deja como nil el current user
  	self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Creación del gravatar
	def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end -%>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shin.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shin' %>
</head>
<body>
	
<%= render 'layouts/header' %>
<div class="container">
	<!-- Inicio flash message -->
	<% flash.each do |key, value| %>
		<%= content_tag(:div, value, class: "alert alert-#{key == :notice ? 'success' : 'error'}") %>
	<% end -%>

	<!-- End flash message -->

	<%= yield %> 

  <%= render 'layouts/footer' %>

  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About')  %>
<h1>About Us</h1>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae, necessitatibus quos minima hic voluptatum sit tempora impedit porro quia delectus earum incidunt sequi beatae dignissimos nihil consectetur aperiam ad aut?
</p>

<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, eveniet minus quae debitis impedit veniam quibusdam voluptatem vel quo laboriosam. Placeat, corporis, sint iusto saepe dicta tenetur quo iure suscipit.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Us</h1>
<p>
	Lorem ipsum Laboris quis tempor elit cillum dolor aute ex aute ex irure nulla irure dolore amet adipisicing ut Ut aliqua do adipisicing occaecat do consequat amet aute qui enim quis minim dolore in voluptate pariatur sed ut tempor et sit Ut anim tempor ullamco deserunt dolor ea in laborum dolor reprehenderit in ad eu Excepteur reprehenderit in mollit consectetur mollit deserunt ut laborum Ut officia deserunt sint et in laboris exercitation magna esse qui eiusmod consequat eiusmod mollit mollit sit qui veniam fugiat dolore fugiat elit elit eiusmod cillum Duis velit enim dolore aute irure laboris ut non consectetur aute elit voluptate dolor est ea sed veniam laboris in in minim consequat amet nisi adipisicing aliquip dolore ad consectetur ullamco sit dolor dolor laboris fugiat occaecat adipisicing dolor in laborum fugiat fugiat veniam laborum quis dolore non aute aute laborum officia consectetur labore nulla cupidatat ullamco amet id minim cupidatat reprehenderit labore non qui aliqua dolor quis nostrud ut reprehenderit in Ut do non in do esse dolore do ad aute et id Ut qui deserunt irure eiusmod dolore sunt magna voluptate aliqua velit esse Duis fugiat in incididunt ad sint id in dolor eu id fugiat do pariatur aliqua culpa velit in sint Ut aliquip irure et dolor pariatur ut adipisicing in laboris culpa id voluptate aute sed Ut reprehenderit cupidatat.
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, magnam, culpa commodi error quos consequatur quis deleniti rem totam dolorem quidem in minima voluptates placeat beatae incidunt reprehenderit. Beatae, sapiente.
</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla, eum, fugiat, optio qui sapiente ratione error corporis magni molestiae accusantium asperiores itaque laudantium architecto explicabo veniam voluptate ad ea neque!</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Bienvenido a Sample App</h1>
	<h2>
		Pagina de inicio para el tutorial de rails
		<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	</h2>
	<%= link_to "Sign up now!", signup_path, class: 'btn btn-large btn-primary' %>
</div>
<%= link_to image_tag('rails.png', alt: 'Rails'), 'http://rubyonrails.org/'%>

app/views/users/_form.html.haml
= simple_form_for @user, html: { multipart: true } do |f|
	= f.input  :name
	= f.input  :email
	= f.input  :password
	= f.input  :password_confirmation, label: "Confirmation"
	= f.input  :avatar, as: :file
	= f.input  :avatar_cache, as: :hidden
	= f.submit value: 'Create my account', class: 'btn btn-primary btn-large'

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>

<div class="row">
	<div class="span6 offset3">
		<h1>Update your profile</h1>

		<%= simple_form_for @user do |f| %>
		  <%= f.input :name %>
			<%= f.input :email %>
			<%= f.input :password %>
			<%= f.input :password_confirmation %>
			<%= f.button :submit, value: 'Save changes', class: 'btn btn-primary' %>
		<% end -%>
		<%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div class="row">
	<div class="span6 offset3">
		<h1>Sign Up</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/users/show.html.haml
- provide :title, @user.name
.row
  %aside.span4
    %h2
      = image_tag @user.avatar.thumb.url
      = @user.name